sudo : required # needs super user permission
services:
  - docker # docker needs to be running

before_install:
  - docker build -t mydockerandtravis -f Dockerfile.dev . # build image

script:
  - docker run -e CI=true mydockerandtravis npm run test # use -- --coverage or -e CI=true (for exiting test)

deploy:
  provider : elasticbeanstalk
  region : "us-east-2"
  app : "summu-docker"
  env : "summu-docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-690943969225"
  bucket_path : "docker-react-aws"
  on:
    branch : main
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : "$AWS_SECRET_KEY"